### ISSUE TITLE
[feat request] alacritty support

### ISSUE THREAD

**Issue by shellRaining** [everviolet/nvim#5]
Thanks for your great work! I quiet like this color scheme. Can you create a config file for alacritty? thanks~

**Comment by comfysage** [comment]
i added a theme with [b1645c5](https://github.com/comfysage/evergarden/commit/b1645c5cc1cc573f28df9a715cc019e453379b24) and changed the colors a bit with [2ff77bc](https://github.com/comfysage/evergarden/commit/b1645c5cc1cc573f28df9a715cc019e453379b24). see which one you prefer :)

**Comment by shellRaining** [comment]
I will take a look, maybe need some time~
