### ISSUE TITLE
[bug report] markdown link highlight error

### ISSUE THREAD

**Issue by shellRaining** [everviolet/nvim#6]
<img width="702" alt="image" src="https://github.com/comfysage/evergarden/assets/111564053/43101c43-a11f-40ce-87b2-68ce82f6e541">

```markdown
其中 `L` 表示字符，他还有一些子类别，比如 `Ll` 表示小写字符，具体可以看 [https://zh.javascript.info/regexp-unicode#unicode-shu-xing-p](https://zh.javascript.info/regexp-unicode#unicode-shu-xing-p)
```

bug report image and code above, the expected behavior is the link has consistent highlighting.

inspectTree output below

<img width="718" alt="image" src="https://github.com/comfysage/evergarden/assets/111564053/5790642b-a990-4594-a509-643f7b98727f">

**Comment by comfysage** [comment]
i can't seem to replicate this issue even with the provided code. maybe try updating your treesitter parsers.

**Comment by shellRaining** [comment]
Sorry I forgot to mention, do not place the cursor in this line, you may need to create a blank line and then place the cursor on the blank line.

**Comment by comfysage** [comment]
> Sorry I forgot to mention, do not place the cursor in this line, you may need to create a blank line and then place the cursor on the blank line.

unfortunately im still not able to replicate the bug you are describing. you might be able to get more help at [the neovim github](https://github.com/neovim/neovim) or [the treesitter github](https://github.com/nvim-treesitter/nvim-treesitter)

**Comment by shellRaining** [comment]
https://github.com/comfysage/evergarden/assets/111564053/16fcb8d6-3fd8-4b6c-a516-ca0617322ebd

It seems to be caused by me enabling spellcheck.

**Comment by comfysage** [comment]
> https://github.com/comfysage/evergarden/assets/111564053/16fcb8d6-3fd8-4b6c-a516-ca0617322ebd
> 
> It seems to be caused by me enabling spellcheck.

so this made me realize it's not actually a bug. the highlighting "issue" is just neovim highlighting spelling mistakes.
