### ISSUE TITLE
[bug report] Highlight group 'NotifyBackground' has no background highlight

### ISSUE THREAD

**Issue by shellRaining** [everviolet/nvim#7]
<img width="759" alt="image" src="https://github.com/comfysage/evergarden/assets/111564053/4e23474d-c2ff-4bff-a169-ee4985ca3b21">

when trigger the notify function, the noice box will occur this bug

**Comment by comfysage** [comment]
nvim-notify uses `winblend = 100` when youve set transparency to 100%. unfortunately there's a bug in neovim where floating windows with winblend of 100 will not be able to properly apply background colors. this means the plugin needs knowledge of the background color you want to use.

you can provide a custom background color like this:
```lua
require('notify').setup({
  background_colour = '#232B2E',
})
```
